# .github/workflows/push-to-replicate.yml
name: Push to Replicate

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'The Replicate model name (e.g., "your-user/your-model")'
        required: true

jobs:
  push_to_replicate:
    name: Push to Replicate
    runs-on: ubuntu-latest
    environment: xverse  # <-- ADD THIS LINE
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Cog and Authenticate
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Push model to Replicate
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "--- Verifying contents of cog.yaml before push ---"
          cat cog.yaml
          echo "----------------------------------------------------"
          cog push r8.im/${{ inputs.model_name }}